# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-02 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(validators=[posts.models.validate_content]),
        ),
    ]
